// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdgrysqujlaxzwgogkvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZ3J5c3F1amxheHp3Z29na3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTQ3NzAsImV4cCI6MjA2ODkzMDc3MH0.43wo9RdNinqUJazVQF4AgkeVNCk0pidom0M41siPaTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});